version: '3.7'

services:
  frontend:
    container_name: vjs-frontend
    build: ./vjs-frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
  backend:
    container_name: vjs-backend
    build: ./vjs-backend
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    container_name: mongo
    ports:
      - 27017:27017
